(rule
 (targets griotte_extracted.ml griotte_extracted.mli)
 (deps
  machine_step.v
  extract_machine.v
  ../theories/opsem/griotte_opsem.vo)
 (action
  (progn
   (run rocq compile -Q ../theories griotte -Q ../machine_utils/theories machine_utils machine_step.v)
   (run rocq compile -Q ../theories griotte -Q ../machine_utils/theories machine_utils extract_machine.v))))
